### ISSUE TITLE
GetTime example not working

### ISSUE THREAD

**Issue by coxtor** [rhasspy/rhasspy-hermes-app#260]
Hi, I am trying to get the getTime example to work. However this error is thrown by the hermes library:
```

[DEBUG:2022-10-18 19:58:47,522] HermesApp: Namespace(host='#########', port=###, username='###', password='####', tls=False, tls_ca_certs=None, tls_certfile=None, tls_keyfile=None, tls_cert_reqs='CERT_REQUIRED', tls_version=None, tls_ciphers=None, site_id=None, debug=True, log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s')
[DEBUG:2022-10-18 19:58:47,523] HermesApp: Connecting to ############
[DEBUG:2022-10-18 19:58:47,527] asyncio: Using selector: EpollSelector
[DEBUG:2022-10-18 19:58:47,529] test: Connected to MQTT broker
[DEBUG:2022-10-18 19:58:47,530] test: Subscribed to hermes/intent/testintent
[ERROR:2022-10-18 19:59:47,296] HermesApp: on_raw_message
Traceback (most recent call last):
  File "/home/v/.local/lib/python3.10/site-packages/rhasspyhermes_app/__init__.py", line 208, in on_raw_message
    nlu_intent = NluIntent.from_json(payload)
  File "/home/v/.local/lib/python3.10/site-packages/dataclasses_json/api.py", line 72, in from_json
    kvs = json.loads(s,
  File "/usr/lib64/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'
```

**Comment by skiingwiz** [comment]
I ran into this too. It looks like the version of dataclasses-json that's being used does not support python 3.9+ where the encoding parameter of json.loads was removed.

I was able to work around this by installing a newer version of dataclasses-json (0.5.7) using `pip install --upgrade dataclasses-json`

**Comment by koenvervloesem** [comment]
Right, now I remember that I needed to bump the version of dataclasses-json to support rhasspy-hermes on Python 3.9: https://github.com/rhasspy/rhasspy-hermes/commit/f8a7b7d685a5c060f77c609ff82d76c9fb3db4e6. Upgrading this library should solve this indeed.
